#include "localization.h"

#include <algorithm>
#include <array>
#include <cstdint>
#include <iterator>
#include <mutex>
#include <vector>

namespace pulse::l10n {
namespace {

struct ZhHantPhrase {
    std::wstring_view simplified;
    const wchar_t* traditional;
};

struct ZhHantChar {
    wchar_t simplified;
    wchar_t traditional;
};

// Generated by tools/zh_tw/gen_zh_tw.py from the Simplified UI literals in src/.
#include "zh_hant_table.inc"

bool Traditional() noexcept { return effective_language() == Language::ZhTW; }

const ZhHantPhrase* FindPhrase(std::wstring_view key) noexcept {
    const auto* end = std::end(kZhHantPhrases);
    const auto* it = std::lower_bound(std::begin(kZhHantPhrases), end, key,
        [](const ZhHantPhrase& phrase, std::wstring_view value) { return phrase.simplified < value; });
    return it != end && it->simplified == key ? it : nullptr;
}

wchar_t FindChar(wchar_t c) noexcept {
    const auto* end = std::end(kZhHantChars);
    const auto* it = std::lower_bound(std::begin(kZhHantChars), end, c,
        [](const ZhHantChar& entry, wchar_t value) { return entry.simplified < value; });
    return it != end && it->simplified == c ? it->traditional : c;
}

// Phrases bucketed by first code unit, longest first, for HantText's scan.
struct PhraseIndex {
    std::vector<const ZhHantPhrase*> phrases;
    std::array<std::pair<uint32_t, uint32_t>, 256> buckets{};  // hashed on the low byte
};

const PhraseIndex& Index() {
    static PhraseIndex index;
    static std::once_flag once;
    std::call_once(once, [] {
        for (const auto& phrase : kZhHantPhrases) index.phrases.push_back(&phrase);
        std::stable_sort(index.phrases.begin(), index.phrases.end(),
            [](const ZhHantPhrase* a, const ZhHantPhrase* b) {
                const unsigned ka = a->simplified.front() & 0xFF, kb = b->simplified.front() & 0xFF;
                if (ka != kb) return ka < kb;
                return a->simplified.size() > b->simplified.size();
            });
        for (uint32_t i = 0; i < index.phrases.size();) {
            const unsigned key = index.phrases[i]->simplified.front() & 0xFF;
            uint32_t j = i;
            while (j < index.phrases.size() &&
                   static_cast<unsigned>(index.phrases[j]->simplified.front() & 0xFF) == key) ++j;
            index.buckets[key] = {i, j};
            i = j;
        }
    });
    return index;
}

} // namespace

bool IsChinese() noexcept {
    const Language language = effective_language();
    return language == Language::ZhCN || language == Language::ZhTW;
}

const wchar_t* Cn(const wchar_t* chinese) noexcept {
    if (!chinese || !Traditional()) return chinese;
    const ZhHantPhrase* phrase = FindPhrase(chinese);
    return phrase ? phrase->traditional : chinese;
}

const wchar_t* Pick(const wchar_t* chinese, const wchar_t* english) noexcept {
    return IsChinese() ? Cn(chinese) : english;
}

std::wstring HantText(std::wstring_view chinese) {
    return Traditional() ? ToTraditional(chinese) : std::wstring(chinese);
}

std::wstring ToTraditional(std::wstring_view chinese) {
    if (chinese.empty()) return {};
    if (const ZhHantPhrase* phrase = FindPhrase(chinese)) return phrase->traditional;
    const PhraseIndex& index = Index();
    std::wstring out;
    out.reserve(chinese.size());
    size_t i = 0;
    while (i < chinese.size()) {
        const auto [first, last] = index.buckets[chinese[i] & 0xFF];
        const ZhHantPhrase* match = nullptr;
        for (uint32_t k = first; k < last; ++k) {
            const ZhHantPhrase* phrase = index.phrases[k];
            // Single-character entries are covered by the character table.
            if (phrase->simplified.size() < 2) continue;
            if (chinese.substr(i, phrase->simplified.size()) == phrase->simplified) {
                match = phrase;
                break;
            }
        }
        if (match) {
            out += match->traditional;
            i += match->simplified.size();
        } else {
            out += FindChar(chinese[i]);
            ++i;
        }
    }
    return out;
}

} // namespace pulse::l10n
